// action types for auth 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CHECK_FAILURE = 'LOGIN_CHECK_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

//action types for initial config
export const INITIAL_CONFIG_SUCCESS = 'INITIAL_CONFIG_SUCCESS';
export const INITIAL_CONFIG_REQUEST = 'INITIAL_CONFIG_REQUEST';
export const INITIAL_CONFIG_ERROR = 'INITIAL_CONFIG_ERROR';
export const INITIAL_MODE_CONFIG_SUCCESS = 'INITIAL_MODE_CONFIG_SUCCESS';
export const INITIAL_MODE_CONFIG_ERROR = 'INITIAL_MODE_CONFIG_ERROR';

//action types to update state data
export const UPDATE_STATE_DATA_SUCCESS = 'UPDATE_STATE_DATA_SUCCESS';
export const UPDATE_STATE_DATA_REQUEST = 'UPDATE_STATE_DATA_REQUEST';
export const UPDATE_STATE_DATA_ERROR = 'UPDATE_STATE_DATA_ERROR';

//action types for events
export const TRIGGER_EVENTS_SUCCESS = 'TRIGGER_EVENTS_SUCCESS';
export const TRIGGER_EVENTS_REQUEST = 'TRIGGER_EVENTS_REQUEST';
export const TRIGGER_EVENTS_ERROR = 'TRIGGER_EVENTS_ERROR';