// action types for auth 
export const LOGINSUCCESS = 'LOGIN_SUCCESS';
export const LOGINREQUEST = 'LOGIN_REQUEST';
export const LOGINERROR = 'LOGIN_ERROR';
export const LOGINCHECKFAILURE = 'LOGIN_CHECK_FAILURE';
export const LOGOUTSUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUTREQUEST = 'LOGOUT_REQUEST';
export const LOGOUTERROR = 'LOGOUT_ERROR';

//action types for initial config
export const INITIALCONFIGSUCCESS = 'INITIAL_CONFIG_SUCCESS';
export const INITIALCONFIGREQUEST = 'INITIAL_CONFIG_REQUEST';
export const INITIALCONFIGERROR = 'INITIAL_CONFIG_ERROR';

//action types to update state data
export const UPDATESTATEDATASUCCESS = 'UPDATE_STATE_DATA_SUCCESS';
export const UPDATESTATEDATAREQUEST = 'UPDATE_STATE_DATA_REQUEST';
export const UPDATESTATEDATAERROR = 'UPDATE_STATE_DATA_ERROR';