export const AUTH_URL = '/auth-service/platform-auth/action/oauth/authenticate'; //url for auth request
export const LANGUAGE_API_URL = '/components/language'; //url to hit get request initially to CORE
export const PPS_MODE_API_URL = 'api/pps_seats'; //url to hit get request initially to CORE
export const PPS_SEATS_API_URL = '/pps_seats'; //url to hit get request initially to CORE
export const VALIDATE_AUTH_URL = '/auth-service/platform-auth/action/oauth/validate';
export const RETREIVE_NEW_TOKEN_URL = "/auth-service/platform-auth/action/oauth/tokenFromRefreshToken" //url to retreive new token
export const PPS_URL = "/pps/";
export const API_URL ='/api';
export const SEATS_URL ='/seats';
export const CALLBACK_URL ='/callback';
