name: PR

on:
  pull_request:

permissions:
  contents: read
  id-token: write

# If POT file needs change, commit that change and stop the workflow
# If not, check that building debian package and docker image works

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      build-vsn: ${{ steps.get-version.outputs.build-vsn }}
    steps:
    - uses: actions/checkout@v3
    - name: Get version
      id: get-version
      run: |
        git fetch --prune --unshallow
        echo "build-vsn=$(git describe --dirty --abbrev=7 --tags --always --first-parent)" >> $GITHUB_OUTPUT
        # Update .npmrc to access gor npm packages
        echo //us-npm.pkg.dev/greymatter-development/npm/:_password=${{ secrets.NPM_PASSWORD }} >> .npmrc
        echo //us-npm.pkg.dev/greymatter-development/npm/:username=${{ secrets.NPM_USERNAME }} >>.npmrc
        echo //us-npm.pkg.dev/greymatter-development/npm/:email=${{ secrets.NPM_EMAIL }} >> .npmrc
    - name: Check
      run: |
        cat .npmrc
    - name: Use Node.js 8
      uses: actions/setup-node@v3
      with:
        node-version: 8
        cache: 'npm'
    - name: npm install
      run: |
        npm install
        npm prune

  build-images:
    name: Build images
    needs: build
    uses: ./.github/workflows/build-images.yml
    with:
      extra_tag: ${{ needs.build.outputs.build-vsn }}
