name: PR

on:
  pull_request:
    branches:
      - develop
      - 'release-**'  
      - '**'  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build images
    uses: ./.github/workflows/build-images.yml
