name: PR

on:
  pull_request:    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Artifacts
    steps: 
    - uses: actions/checkout@v3
    - name: Use .npmrc
      uses: bduff9/use-npmrc@v1.1
      with:
        dot-npmrc: ${{ secrets.DOT_NPMRC }}
    - name: Use Node.js 8
      uses: actions/setup-node@v3
      with:
        node-version: 8
        cache: 'npm'
    - name: npm install
      run: |
        npm install
        npm prune
    - name: Run a test build # Build but dont push (This will result in an error if syntax is wrong) 
      run : |
        npm run build
